name: Enterprise Data Pipeline CI

# Trigger this workflow on every push or pull request to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Repository
      uses: actions/checkout@v3

    - name: Set up Enterprise Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: 'pip'

    - name: Install Java (Required for PySpark)
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: Install Project Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pyspark==3.5.0

    - name: Enforce Code Quality (Flake8)
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Execute PySpark Unit Tests (Pytest)
      run: |
        pytest tests/ -v